FROM ubuntu:latest

RUN echo "==> Upgrading apk and installing system utilities ...." \
 && apt -y update \
 && apt-get -y install sudo 

RUN echo "==> Install Git ...." \ 
 && sudo DEBIAN_FRONTEND=noninteractive apt install -y git-all

RUN echo "==> Installing Python3 and pip ...." \  
 && apt-get install python3 -y \
 && apt install python3-pip -y

RUN echo "==> Installing psutil ...." \  
 && python3 -m pip install psutil

RUN echo "==> Installing Jinja2 ...." \  
 && python3 -m pip install jinja2

RUN echo "==> Installing WMI ...." \  
 && python3 -m pip install wmi

ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

RUN echo "==> Git Clone..." \
  && git clone https://github.com/automateyournetwork/squeegee.git

VOLUME /MindMaps/Windows/ /MindMaps/Windows/

CMD  [ "python3", "./squeegee/MindMaps/Squeegee.py" ]